language: python
python:
  - "3.6"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels http://ssb.stsci.edu/astroconda
  - conda config --add channels http://astroconda.gemini.edu/public
  - conda create -n dragons python=3.6 dragons stsci
  - conda activate dragons
  - pip install -r requirements.txt -e .

script:
  - pytest .
