name: ci

on:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: nat1405/niri:0.1
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pytest, in dragons env, in container.
        run: |
          conda run -n dragons pytest .
