name: ci

on:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: nat1405/niri:0.1
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pytest, in dragons env, in container.
        run: |
          conda run -n dragons pytest .

  deploy:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - name: Get current datetime
        id: date
        run: echo "::set-output name=date::$(date +%Y%m%d-%H%M%S)"

      - name: Checkout Dockerfile repo
        uses: actions/checkout@v2
        with:
          repository: ijiraq/gemini_processing
          ref: niri
          path: gemini_processing

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: gemini_processing/niri/dockerfiles/arcade-niri/
          file: gemini_processing/niri/dockerfiles/arcade-niri/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/niri:0.1
          build-args: |
            TIMESTAMP=${{ steps.date.outputs.date }}
