name: ci

on:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: nat1405/niri:0.1
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pytest, in dragons env, in container.
        run: |
          conda run -n dragons pytest .

  deploy:
    runs-on: ubuntu-latest
    needs: pytest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout niriPipe repo
        uses: actions/checkout@v2

      - name: Checkout Dockerfile repo
        uses: actions/checkout@v2
        with:
          repository: ijiraq/gemini_processing
          ref: niri
          path: gemini_processing

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build
        working-directory: gemini_processing/dockerfiles/arcade-niri
        run: |
          make

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        run: |
          docker push nat1405/niri:0.1
